// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQFOARPcrH3JU00mQPx15egPPyV_ya6q0',
    appId: '1:356235988:web:3dad9e3831e4a691005941',
    messagingSenderId: '356235988',
    projectId: 'thananan-project',
    authDomain: 'thananan-project.firebaseapp.com',
    storageBucket: 'thananan-project.firebasestorage.app',
    measurementId: 'G-LM6XWXBCFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwTkAEZILDHawc33RiD5IQTi1n7qRZNNU',
    appId: '1:356235988:android:684642fc7acd5334005941',
    messagingSenderId: '356235988',
    projectId: 'thananan-project',
    storageBucket: 'thananan-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsL2Yc_mFLzhZYlcrWBycL9xPBKao6Ge4',
    appId: '1:356235988:ios:bfa92da2c6505b42005941',
    messagingSenderId: '356235988',
    projectId: 'thananan-project',
    storageBucket: 'thananan-project.firebasestorage.app',
    iosBundleId: 'com.example.nattanon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsL2Yc_mFLzhZYlcrWBycL9xPBKao6Ge4',
    appId: '1:356235988:ios:bfa92da2c6505b42005941',
    messagingSenderId: '356235988',
    projectId: 'thananan-project',
    storageBucket: 'thananan-project.firebasestorage.app',
    iosBundleId: 'com.example.nattanon',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQFOARPcrH3JU00mQPx15egPPyV_ya6q0',
    appId: '1:356235988:web:0a0aaef9cdfc465b005941',
    messagingSenderId: '356235988',
    projectId: 'thananan-project',
    authDomain: 'thananan-project.firebaseapp.com',
    storageBucket: 'thananan-project.firebasestorage.app',
    measurementId: 'G-XPXJGHB3TZ',
  );
}
